### ISSUE TITLE
Script Name wrapped although it has enough space

### ISSUE THREAD

**Issue by LoTwT** [alexzhang1030/npms#1]
Like the image, script name should be in one line.

<img width="1491" alt="image" src="https://user-images.githubusercontent.com/50254496/191193250-36d001f8-b65f-45e9-bb5e-2bd062879ac2.png">

**Comment by alexzhang1030** [comment]
got it.

**Comment by alexzhang1030** [comment]
will fixed on next version

**Comment by alexzhang1030** [comment]
becuase i did't find API in `temir`, so there is no way to fundamentally solve this problem.

i expanded the width, maybe it will display correctly in most cases

**Comment by alexzhang1030** [comment]
If it could not showing correctly, PLEASE reopen it.
