### ISSUE TITLE
Can it interact with the terminal to run the selected script ?

### ISSUE THREAD

**Issue by LoTwT** [alexzhang1030/npms#2]
Can it is designed `Arrow Top` or `Arrow Bottom` to run the script ?

**Comment by alexzhang1030** [comment]
Maybe i will submit a PR to `temir` for implementing this feature

**Comment by alexzhang1030** [comment]
Task: 
- [x] can select and execute
- [ ] improve appearence
- [ ] improve behaivor

**Comment by alexzhang1030** [comment]
v0.2.0 can execute scripts, have a try :)
